// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EMSApi.Models;

public partial class AuditLog:BaseEntity
{
    [Key]
    public int AuditLogId { get; set; }

    [StringLength(50)]
    public string EntityName { get; set; }

    public int? EntityId { get; set; }

    [StringLength(50)]
    public string Action { get; set; }

    [StringLength(50)]
    public string PerformedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PerformedAt { get; set; }

    public string Changes { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }
}