// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EMSApi.Models;

[PrimaryKey("EmployeeId", "ProjectId")]
public partial class EmployeeProject:BaseEntity
{
    [Key]
    public int EmployeeId { get; set; }

    [Key]
    public int ProjectId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AssignedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeProjects")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("EmployeeProjects")]
    public virtual Project Project { get; set; }
}