// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EMSApi.Models;

public partial class Project
{
    [Key]
    public int ProjectId { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    public string Description { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; } = new List<EmployeeProject>();
}