// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EMSApi.Models;

[Index("Username", Name = "UQ__Users__536C85E4E70D9EC6", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserId { get; set; }

    [StringLength(50)]
    public string Username { get; set; }

    [StringLength(256)]
    public string PasswordHash { get; set; }

    [StringLength(20)]
    public string Role { get; set; }
}