name: EMS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # ✅ Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v3

    # ✅ Install .NET 9 SDK (preview)
    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.100-preview.3' # or use latest preview available

    # ✅ Display installed .NET info
    - name: Display .NET version
      run: dotnet --info

    # ✅ Restore NuGet packages
    - name: Restore dependencies
      run: dotnet restore EMSApi.sln

    # ✅ Build the solution
    - name: Build solution
      run: dotnet build EMSApi.sln --no-restore --configuration Release

    # ✅ Run unit tests targeting .NET 9
    - name: Run tests
      run: dotnet test EMSApiTest/EMSApi.Test.csproj --no-build --configuration Release --verbosity normal --framework net9.0

    # ✅ Generate TRX test report
    - name: Run tests and collect report
      run: dotnet test EMSApiTest/EMSApi.Test.csproj --logger trx --results-directory TestResults

    # ✅ Publish test results to GitHub UI
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: NUnit Test Results
        path: TestResults/*.trx
        reporter: dotnet-trx
